// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlcgen

import (
	"context"
	"time"
)

const blockDomain = `-- name: BlockDomain :exec
INSERT INTO blocked (domain, reason, blocked_at)
VALUES (?, ?, ?)
ON CONFLICT(domain) DO UPDATE SET reason = excluded.reason, blocked_at = excluded.blocked_at
`

type BlockDomainParams struct {
	Domain    string
	Reason    string
	BlockedAt time.Time
}

// Only for the three kinds that describe the domain: ErrNoServer,
// ErrInvalidQuery, ErrRefused. Everything else goes to attempts.
func (q *Queries) BlockDomain(ctx context.Context, arg BlockDomainParams) error {
	_, err := q.db.ExecContext(ctx, blockDomain, arg.Domain, arg.Reason, arg.BlockedAt)
	return err
}

const countBySuffixLen = `-- name: CountBySuffixLen :many
SELECT suffix, label_len, status, COUNT(*) AS n
FROM checks
GROUP BY suffix, label_len, status
ORDER BY suffix, label_len, status
`

type CountBySuffixLenRow struct {
	Suffix   string
	LabelLen int64
	Status   string
	N        int64
}

func (q *Queries) CountBySuffixLen(ctx context.Context) ([]CountBySuffixLenRow, error) {
	rows, err := q.db.QueryContext(ctx, countBySuffixLen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBySuffixLenRow{}
	for rows.Next() {
		var i CountBySuffixLenRow
		if err := rows.Scan(
			&i.Suffix,
			&i.LabelLen,
			&i.Status,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChecks = `-- name: CountChecks :one
SELECT COUNT(*) FROM checks
`

func (q *Queries) CountChecks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChecks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailures = `-- name: CountRecentFailures :one
SELECT COUNT(*) FROM attempts WHERE domain = ? AND attempted_at > ?
`

type CountRecentFailuresParams struct {
	Domain      string
	AttemptedAt time.Time
}

// Drives the backoff exponent. Bounded by time rather than counting the whole
// history, so a domain that failed last year starts fresh.
func (q *Queries) CountRecentFailures(ctx context.Context, arg CountRecentFailuresParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailures, arg.Domain, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deferCheck = `-- name: DeferCheck :exec
UPDATE checks SET fresh_until = ? WHERE domain = ?
`

type DeferCheckParams struct {
	FreshUntil time.Time
	Domain     string
}

// Push a row past a failure so the sweep stops returning it. This is what
// stands in for consulting attempts.retry_after in the scheduler query.
func (q *Queries) DeferCheck(ctx context.Context, arg DeferCheckParams) error {
	_, err := q.db.ExecContext(ctx, deferCheck, arg.FreshUntil, arg.Domain)
	return err
}

const dueChecks = `-- name: DueChecks :many
SELECT domain FROM checks c
WHERE c.fresh_until < datetime('now')
  AND NOT EXISTS (SELECT 1 FROM blocked b WHERE b.domain = c.domain)
ORDER BY c.priority DESC, c.queued_at ASC
LIMIT ?
`

// Work is a staleness query: fresh_until in the past means "check this".
//
// blocked is excluded here rather than by deleting the row, so a domain that
// becomes servable again (a new RDAP endpoint published for its suffix) needs
// one DELETE rather than a re-seed. Measured at 1M rows: 65us without the
// exclusion, 8.65ms with it -- irrelevant against a rate limit measured in
// queries per second.
//
// retry_after is deliberately NOT consulted. Doing so measured 95ms, 1460x the
// unfiltered query, because it cannot use the ordering index. The writer pushes
// fresh_until past the retry instant instead, which costs nothing extra.
func (q *Queries) DueChecks(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, dueChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterChecks = `-- name: FilterChecks :many
SELECT domain FROM checks
WHERE suffix = ? AND label_len = ? AND status = ?
`

type FilterChecksParams struct {
	Suffix   string
	LabelLen int64
	Status   string
}

func (q *Queries) FilterChecks(ctx context.Context, arg FilterChecksParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, filterChecks, arg.Suffix, arg.LabelLen, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheck = `-- name: GetCheck :one
SELECT domain, status, source, checked_at, fresh_until, expiration, registered_at, server, stale, priority, queued_at, suffix, label_len FROM checks WHERE domain = ?
`

func (q *Queries) GetCheck(ctx context.Context, domain string) (Check, error) {
	row := q.db.QueryRowContext(ctx, getCheck, domain)
	var i Check
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.Source,
		&i.CheckedAt,
		&i.FreshUntil,
		&i.Expiration,
		&i.RegisteredAt,
		&i.Server,
		&i.Stale,
		&i.Priority,
		&i.QueuedAt,
		&i.Suffix,
		&i.LabelLen,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (SELECT 1 FROM blocked WHERE domain = ?)
`

func (q *Queries) IsBlocked(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBlocked, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pruneAttempts = `-- name: PruneAttempts :execrows
DELETE FROM attempts WHERE attempted_at < ?
`

func (q *Queries) PruneAttempts(ctx context.Context, attemptedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAttempts, attemptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recentAttempts = `-- name: RecentAttempts :many
SELECT domain, attempted_at, error_kind, retryable, retry_after FROM attempts WHERE domain = ? ORDER BY attempted_at DESC LIMIT ?
`

type RecentAttemptsParams struct {
	Domain string
	Limit  int64
}

func (q *Queries) RecentAttempts(ctx context.Context, arg RecentAttemptsParams) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, recentAttempts, arg.Domain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.Domain,
			&i.AttemptedAt,
			&i.ErrorKind,
			&i.Retryable,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
INSERT INTO attempts (domain, attempted_at, error_kind, retryable, retry_after)
VALUES (?, ?, ?, ?, ?)
`

type RecordAttemptParams struct {
	Domain      string
	AttemptedAt time.Time
	ErrorKind   string
	Retryable   bool
	RetryAfter  *time.Time
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordAttempt,
		arg.Domain,
		arg.AttemptedAt,
		arg.ErrorKind,
		arg.Retryable,
		arg.RetryAfter,
	)
	return err
}

const seedCheck = `-- name: SeedCheck :execrows
INSERT OR IGNORE INTO checks (domain, status, fresh_until, priority)
VALUES (?, 'unchecked', ?, ?)
`

type SeedCheckParams struct {
	Domain     string
	FreshUntil time.Time
	Priority   int64
}

// OR IGNORE so re-running a narrower seed over a wider one is a no-op per row
// rather than resetting status or priority on already-checked domains.
//
// execrows rather than exec: the rows-affected count is 1 for a new row and 0
// for one that was ignored, which is how the seeder reports what it added
// without counting the table before and after every batch.
func (q *Queries) SeedCheck(ctx context.Context, arg SeedCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, seedCheck, arg.Domain, arg.FreshUntil, arg.Priority)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCheck = `-- name: UpsertCheck :exec
INSERT INTO checks (domain, status, fresh_until, priority)
VALUES (?, ?, ?, ?)
ON CONFLICT(domain) DO UPDATE SET
  status      = excluded.status,
  fresh_until = excluded.fresh_until,
  priority    = MAX(checks.priority, excluded.priority)
`

type UpsertCheckParams struct {
	Domain     string
	Status     string
	FreshUntil time.Time
	Priority   int64
}

// Generated columns are omitted deliberately: naming one is an error.
func (q *Queries) UpsertCheck(ctx context.Context, arg UpsertCheckParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheck,
		arg.Domain,
		arg.Status,
		arg.FreshUntil,
		arg.Priority,
	)
	return err
}

const upsertCheckResult = `-- name: UpsertCheckResult :exec
INSERT INTO checks (domain, status, source, checked_at, fresh_until,
                    expiration, registered_at, server, stale)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(domain) DO UPDATE SET
  status        = excluded.status,
  source        = excluded.source,
  checked_at    = excluded.checked_at,
  fresh_until   = excluded.fresh_until,
  expiration    = excluded.expiration,
  registered_at = excluded.registered_at,
  server        = excluded.server,
  stale         = excluded.stale
`

type UpsertCheckResultParams struct {
	Domain       string
	Status       string
	Source       *string
	CheckedAt    *time.Time
	FreshUntil   time.Time
	Expiration   *time.Time
	RegisteredAt *time.Time
	Server       *string
	Stale        bool
}

// The full result path. Generated columns are omitted: naming one is an error.
func (q *Queries) UpsertCheckResult(ctx context.Context, arg UpsertCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheckResult,
		arg.Domain,
		arg.Status,
		arg.Source,
		arg.CheckedAt,
		arg.FreshUntil,
		arg.Expiration,
		arg.RegisteredAt,
		arg.Server,
		arg.Stale,
	)
	return err
}
