// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlcgen

import (
	"context"
	"time"
)

const dueChecks = `-- name: DueChecks :many
SELECT domain FROM checks
WHERE fresh_until < datetime('now')
ORDER BY priority DESC, queued_at ASC
LIMIT ?
`

func (q *Queries) DueChecks(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, dueChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterChecks = `-- name: FilterChecks :many
SELECT domain FROM checks
WHERE suffix = ? AND label_len = ? AND status = ?
`

type FilterChecksParams struct {
	Suffix   string
	LabelLen int64
	Status   string
}

func (q *Queries) FilterChecks(ctx context.Context, arg FilterChecksParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, filterChecks, arg.Suffix, arg.LabelLen, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheck = `-- name: GetCheck :one
SELECT domain, status, source, checked_at, fresh_until, expiration, registered_at, server, stale, priority, queued_at, suffix, label_len FROM checks WHERE domain = ?
`

func (q *Queries) GetCheck(ctx context.Context, domain string) (Check, error) {
	row := q.db.QueryRowContext(ctx, getCheck, domain)
	var i Check
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.Source,
		&i.CheckedAt,
		&i.FreshUntil,
		&i.Expiration,
		&i.RegisteredAt,
		&i.Server,
		&i.Stale,
		&i.Priority,
		&i.QueuedAt,
		&i.Suffix,
		&i.LabelLen,
	)
	return i, err
}

const upsertCheck = `-- name: UpsertCheck :exec
INSERT INTO checks (domain, status, fresh_until, priority)
VALUES (?, ?, ?, ?)
ON CONFLICT(domain) DO UPDATE SET
  status      = excluded.status,
  fresh_until = excluded.fresh_until,
  priority    = MAX(checks.priority, excluded.priority)
`

type UpsertCheckParams struct {
	Domain     string
	Status     string
	FreshUntil time.Time
	Priority   int64
}

// Generated columns are omitted deliberately: naming one is an error.
func (q *Queries) UpsertCheck(ctx context.Context, arg UpsertCheckParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheck,
		arg.Domain,
		arg.Status,
		arg.FreshUntil,
		arg.Priority,
	)
	return err
}
