// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Attempt struct {
	Domain      string
	AttemptedAt time.Time
	ErrorKind   string
	Retryable   bool
	RetryAfter  *time.Time
}

type Blocked struct {
	Domain    string
	Reason    string
	BlockedAt time.Time
}

type Check struct {
	Domain       string
	Status       string
	Source       *string
	CheckedAt    *time.Time
	FreshUntil   time.Time
	Expiration   *time.Time
	RegisteredAt *time.Time
	Server       *string
	Stale        bool
	Priority     int64
	QueuedAt     time.Time
	Suffix       string
	LabelLen     int64
}

type Server struct {
	Origin              string
	LastSuccess         *time.Time
	LastFailure         *time.Time
	ConsecutiveFailures int64
	RateLimitedUntil    *time.Time
	SupportsSearch      *bool
}
