// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	sqltime "github.com/khinshankhan/nomex/data/sqltime"
)

type Attempt struct {
	Domain      string
	AttemptedAt sqltime.UTC
	ErrorKind   string
	Retryable   bool
	RetryAfter  *sqltime.UTC
}

type Blocked struct {
	Domain    string
	Reason    string
	BlockedAt sqltime.UTC
}

type Check struct {
	Domain       string
	Status       string
	Source       *string
	CheckedAt    *sqltime.UTC
	FreshUntil   sqltime.UTC
	Expiration   *sqltime.UTC
	RegisteredAt *sqltime.UTC
	Server       *string
	Stale        bool
	Priority     int64
	QueuedAt     sqltime.UTC
	Suffix       string
	LabelLen     int64
}

type Server struct {
	Origin              string
	LastSuccess         *sqltime.UTC
	LastFailure         *sqltime.UTC
	ConsecutiveFailures int64
	RateLimitedUntil    *sqltime.UTC
	SupportsSearch      *bool
}
